### ISSUE TITLE
storing nested comments

### ISSUE THREAD

**Issue by Ziyta** [JosephPrichard/Pantheon#4]
I just had a quick question about the way you have stored the comments / nesting. 

Did you use the [ltree extension](https://www.postgresql.org/docs/current/ltree.html) avaliable in postgres?

Or was it just the simple case of storing the root post and a parent id for each comment and building an array of those comments which repersents a multiple comment tree, which you then convert into an actual trees in the front end?

Thanks!

**Comment by JosephPrichard** [comment]
I used the second strategy. The code that gets the result set into a tree structure is on the backend because the comments are serverside rendered.

Hope this helps!
